import "bootstrap/dist/css/bootstrap.css"; // Add this line
import "../styles/globals.css";
import type { AppProps } from "next/app";
import Layout from "../components/layout";
import Script from "next/script";
import Head from "next/head";
import Navbar from "../components/navbar";
import Header from "../components/header";
import type { NextPage } from "next";
import Footer from "@/components/footer";

// For layout Component
export type NextPageWithLayout = NextPage & {
  getLayout?: (page: React.ReactElement) => React.ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout ?? ((page) => page);

  return (
    <>
      <Head>
        <title>Bank App</title>
        <meta name="description" content="Generated by sonny" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
      </Head>
      <Script
        id="bootstrap-cdn"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      />
      <Navbar></Navbar>
      <Header></Header>
      <Layout>
        <Component {...pageProps} />
      </Layout>
      <Footer></Footer>
    </>
  );
}
